nginx:
    build: ./Docker-nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./Docker-node
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./Docker-node
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./Docker-node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"